const s= 10;
let t = 10;
var u = 10;
const d= "string";
let e = undefined;
var f = null;
const g= NaN;
let h = 10;
var z = 10;
const j= 10;
let k = "string";
var l = 10;
const m= 10;
let n = null;
var o = 10;
const p= undefined;
let q = 10;
var r = 10;
console.log(s,t,u,d,e,f,g,h,j,k,l,m,n,o,p,q,r)
